version: '3'

services:
  web:
    restart: on-failure
    depends_on:
      - pgdb
    environment:
      DATABASE_URL: "postgres://postgres:postgres@posgres/postgres"
    build: .
    command: cargo run
    volumes:
      - .:/usr/src/actix-demo
    ports:
      - 8000:8000
    links:
      - pgdb
  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
